name: Feature Request
description: Suggest a new idea or enhancement for Cell Powered
title: "[FEATURE] "
labels: []

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        
        Thanks for helping make **Cell Powered** better! Please check existing requests before submitting to avoid duplicates.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: |
        Please provide a clear description of the problem or pain point this feature would address.
      placeholder: "I'm frustrated when... or It would be great if..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: |
        How should Boring Notch handle this? Describe the behavior, UI, or interaction you imagine in detail.
      placeholder: "I would like the app to..."
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use cases & user scenarios
      description: |
        Describe specific scenarios where this feature would be valuable. Who would benefit from this and how often would it be used?
      placeholder: "This would help users who..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context & screenshots
      description: |
        Add any other context, mockups, wireframes, or screenshots about the feature request here. Visuals are incredibly helpful!
        
        You can drag and drop images directly into this field.
      placeholder: "Here is a mockup of how the feature should look..."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: "Please confirm the following before submitting:"
      options:
        - label: "I have searched existing issues to ensure this isn't a duplicate"
          required: true
        - label: "I have provided sufficient detail for the developer to understand the request"
          required: true
